# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "ai-sheets-analyst"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
image_transformation = { enabled = true }

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:54321/functions/v1/oauth-callback"]
jwt_expiry = 3600

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

# Functions you actually serve (each has its own folder with index.ts)
[functions.plan]
verify_jwt = false

[functions.preview]
verify_jwt = false

[functions.apply]
verify_jwt = false

[functions.undo]
verify_jwt = false

[functions.reserve]
verify_jwt = false

[functions.release]
verify_jwt = false

[functions.explain]
verify_jwt = false

[functions.pull]
verify_jwt = false

[functions.oauth-start]
verify_jwt = false

[functions.oauth-callback]
verify_jwt = false
